### ISSUE TITLE
Exceptions @ console usage

### ISSUE THREAD

**Issue by glotchimo** [houbie/greenfoot#3]
Tried to get the motor running with the Groovy console and such, but I got a whole load of errors. Any ideas?

Sidenote: I did remove all Mac OSX blocks because they were obsolete and unused and only caused errors.

> import greenfoot.core.Simulation

greenfoot.export.GreenfootScenarioMain.main()
world = greenfoot.core.WorldHandler.instance.world
simulation = Simulation.instance

Result: java.lang.ClassNotFoundException: EmptyWorld
	//excluded
//excluded

**Comment by houbie** [comment]
This Greenfoot experiment dates from quite a while ago and I don't have any idea what changed since then.
To be honest, I abandoned Greenfoot/Java because both the language and the editor are not suitable for teaching (compared to the Python eco system).
This repository only exists as reference.
